export class Select2APIEndpoint {
  static readonly Select2 = {
    GetEntitySelect2List: '/Entity/GetSelect2List',
    GetApPymentTypeSelect2List: '/Lookup/ApPaymentType',
    GetApVendorSelect2List: '/ApVendor/GetVendorSelect2List',
    GetArMiscStatusSelect2List: '/Lookup/ArMiscPosted',
    GetSpBenSelect2List: '/SpBeneficents/GetSpBeneficentsSelect2List',
    GetProjectNameSelect2List: '/ScProject/GetScProjectSelect2List',
    GetCollectorsSelect2List: '/ApMiscPaymentHeader/GetCollectorsSelect2List',
    GetvendorSelect2List: '/ApVendor/GetvendorSelect2List',
    ReceiptIdentifierSelect2List: '/Lookup/ReceiptIdentifier',
    GetFndCountrySelect2List: '/FndCountry/GetSelect2List',
    GetBranchSelect2List: '/FinancialReports/GetBranchSelect2List',
    GetDepartmentSelect2List: '/Department/Select2',
    GetGlAccountSelect2List: '/GlAccount/GetGlAccountSelect2List',
    GetSpBeneficentsSelect2List: '/SpBeneficents/GetSpBeneficentsSelect2List',
    GetGlPeriodDetailSelect2List: '/GlPeriodDetails/GetGlPeriodDetailSelect2List',
    GetInvoiceTypeSelect2List: '/VwApInvoiceHd/GetInvoiceTypeSelect2List',
    GetMiscPaymentStatusSelect2List: '/Lookup/Posted',
    GetApVendorStatusSelect2List: '/Lookup/ApVendorStatus',
    GetJvSourceSelect2List: '/Lookup/JvSource',
    GetJeStatusSelect2List: '/Lookup/JeStatus',
    GetCurrencySelect2List: '/Lookup/Currency',
    SpOfficesSelect2List: '/Lookup/SpOffices',
    SpCasesPaymentSelect2List: '/Lookup/GetSpCasesPaymentSelect2List',
    PaymentStatusSelect2List: '/Lookup/PaymentStatus',
    GetSpBenSelect2ListBYEntityID: '/SpBeneficents/GetSpBeneficentsSelect2List',
    GetSpContractsNoSelect2List: '/SpContracts/GetContractNoSelect2List',
    GetContractStatusSelect2List: '/SpContracts/GetContractStatusSelect2List',
    GetBenefPaymentTypeSelect2List: '/SpContracts/GetBenefPaymentTypeSelect2List',
    GetGlPeriodYearsSelect2List: '/GlPeriodYears/GetGlPeriodYearsSelect2List',
    ChartTypeRevenueAndExpenses: '/ChartType/RevenueAndExpenses',
  };
}

